language: node_js
node_js:
    - "10"
    - "11"

install:
    - npm ci

jobs:
    include:
        - stage: test
          env:
            - NODE_ENV=test
          name: "Linting"
          script: npm run lint
        - stage: build
          name: "Building Production"
          script: npm run build

stages:
    - test
    - build

cache: npm
