language: node_js
node_js:
    - "10"
    - "11"
    - "12"

env:
    - NODE_ENV=test

install:
    - npm install
    - npm run bootstrap
    - npm run build:frontend

jobs:
    include:
        - stage: "Tests"
          node_js: 12
          name: "Linting"
          script: npm run lint
        - script: npm run test:unit
          name: "Unit Tests"
        # - stage: build
        #   name: "Building Production Node 10"
        #   script: npm run bootstrap && npm run build
        #   env:
        #     - NODE_ENV=development
        #   node_js: "10"
        # - stage: build
        #   name: "Building Production Node 11"
        #   script: npm run bootstrap && npm run build
        #   env:
        #     - NODE_ENV=development
        #   node_js: "11"


cache: npm
