language: node_js
node_js:
    - "10"
    - "11"
    - "12"

env:
    - NODE_ENV=test

install:
    - npm install

script: npm run lint

jobs:
    include:
        - stage: test
        - stage: build
          name: "Building Production Node 10"
          script: npm install && npm run bootstrap && npm run build
          env:
            - NODE_ENV=production
          node_js: "10"
        - stage: build
          name: "Building Production Node 11"
          script: npm install && npm run bootstrap && npm run build
          env:
            - NODE_ENV=production
          node_js: "11"

stages:
    - test
    - build

cache: npm
