language: node_js
node_js:
    - "10"
    - "11"
    - "12"

install:
    - npm install

jobs:
    include:
        - stage: test
          env:
            - NODE_ENV=test
          name: "Linting"
          script: npm run lint
        - stage: build
          name: "Building Production"
          script: npm run build
          node_js:
            - "10"
            - "11"

stages:
    - test
    - build

cache: npm
