version: '3.7'
services:

    app:
        build:
            context: .
        command: >
            ./node_modules/.bin/concurrently
                "npm -C ./frontend start"
                "npm -C ./server run start:dev"
        volumes:
            - "./server/src:/app/server/src"
            - "./frontend/src:/app/frontend/src"
            - "./dist:/app/dist"
        ports:
            - "3010:3010"
            - "5858:5858"
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
        # environment:
        #   - SETUP_DEFAULT_USER=true
