version: '3.7'

services:
    app:
        build: .
        volumes:
            - "./storage.sqlite3:/app/storage.sqlite3"
        ports:
            - "80:3010"
            - "5858:5858"
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
        # environment:
        #   - SETUP_DEFAULT_USER=true
