version: '3.7'

services:
    app:
        build: .
        container_name: alexnotes
        volumes:
            - "./config.js:/app/config.js:ro"
            # Add your local git config to the Docker container
            - "~/.gitconfig:/etc/gitconfig:ro"
            # Mount your SSH key if necessary
            - "~/.ssh/id_rsa:/home/alexnotes/.ssh/id_rsa:ro"
            # Mount the notes repo and user database to an external folder
            - "~/.alexnotes:/home/alexnotes/.alexnotes"
        ports:
            - "80:3010"
            - "5858:5858"
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
        # environment:
        #   - SETUP_DEFAULT_USER=true
